### PR TITLE
Tinkers Construct Integration

### PR DESCRIPTION
**Pull request by Gordon-Frohman**
Opening this PR for easier progress tracking
What is currently done:
- All the materials are added (they all have stats of iron for now)
- All the textures present in 1.12.2 version are backported
- All the recipes are working properly
- All the tools are properly textured
- Molten metal blocks are fully textured
- Fiery Blood/Tears can be poured into TiC tanks and into smeltery to create molten fiery metal or used as a fuel. You can also extract it from tanks with glass bottles to get your blood back
- Nuggets made of Fiery metal and Knightmetal with all recipes implemented
- Every added liquid can be poured into a bucket
- Brand new tutorial book written in the style of Forgotten Explorer's notebooks. Will be given to player once he/she collects any of the materials from the integration. Translated into English and Russian
- English and Russian language files (feel free to add yours if you want to)
- All material traits:
- **Twilit** for the TF tools (+2 speed inside of TF and +2 damage outside of it)
- **Precipitate** for Naga scale tools (the less health the owner has, the faster the tools become, maximum bonus - +100%)
- **Synergy** for Steeleaf tools (they regenerate their health, with the speed depending of the amount of steeleafs in your toolbar)
- **Stalwart** for Knightmetal tools (10% chance of giving a Resistance effect on hit)
- **Veiled** for raven feather arrows (they turn invisible once fired)

What has to be done:
- Proper stats tuning (will be done in a separate PR in the future)

### CODE REVIEW

**Review by Alastors — APPROVED** [review]
Looks good from the English side, would like another Russian approval though as well as a second set of eyes to look over the code to make sure I didn't miss anything glaring

**Comment by Alastors** [comment]
I especially like the raven fletching though, fletching and string are two parts that almost never get new parts, and even if the effect is useless outside of PVP, it's pretty neat regardless

**Comment by Gordon-Frohman** [comment]
> I especially like the raven fletching though, fletching and string are two parts that almost never get new parts, and even if the effect is useless outside of PVP, it's pretty neat regardless

Thank you, but I'm just backporting stuff from 1.12.2 :)

**Comment by YannickMG** [comment]
Once this is merged, you could consider editing the tinkers construct manuals in the core mod to document materials and traits.

**Comment by Gordon-Frohman** [comment]
> Once this is merged, you could consider editing the tinkers construct manuals in the core mod to document materials and traits.

I thought of doing it from here actually. I hope it is possible. Will add it into to-do list anyway

**Comment by YannickMG** [comment]
> > Once this is merged, you could consider editing the tinkers construct manuals in the core mod to document materials and traits.
> 
> I thought of doing it from here actually. I hope it is possible. Will add it into to-do list anyway

You would need to add an entirely new book to do it outside of the core mod, as right now these books are defined in xml files, and the core mod should run after TF.

They were of course originally defined in Tinker's Construct but I overrode them in the core mod to be able to put any mod's items in the books, and to make them localizable through lang files. Right now they're added here: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/tinkersConstruct/TiCoLoader.java

**Comment by Gordon-Frohman** [comment]
Okay, I'll figure something out
Thank you for the example

**Review by Alastors — APPROVED** [review]
I'm on mobile, so maybe I could've missed something, but looks fine to me?

**Comment by Caedis** [comment]
Related issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15589

Also `com.mojang.realmsclient.gui.ChatFormatting` should be changed out for `net.minecraft.util.EnumChatFormatting` as the former does not exist on servers.

**Pull request merged**
