### PR TITLE
Dedicated server crash fix

### LINKED ISSUE #45: Crash on dedicated server
A client-side class is being loaded server-side here:

https://github.com/GTNewHorizons/twilightforest/blob/ef82996cddaeab9b579d740fb382cc15be6ae44d/src/main/java/twilightforest/integration/TFTinkerConstructIntegration.java#L838-L849

Namely `net.minecraft.client.Minecraft`.

### PR DESCRIPTION
**Pull request by Gordon-Frohman**
Added client side check
That should fix #45

### CODE REVIEW

**Review by AbdielKavash — CHANGES_REQUESTED** [review]
Does not crash on opening the book anymore, but clicking the "next" button twice crashes again.

https://mclo.gs/alM22OP

**Comment by Caedis** [comment]
confirmed

**Comment by Gordon-Frohman** [comment]
Oh no, this thing again
Two questions: you're both playing on English, right?
And does the crash happends on client or on server?

**Comment by Caedis** [comment]
happened in a SP world, and English

**Comment by Gordon-Frohman** [comment]
> happened in a SP world, and English

Should be easy for me to recreate then, thanks

**Comment by Gordon-Frohman** [comment]
Fixed the crash for me
But, @Caedis, @AbdielKavash, I need you to check it

**Comment by Caedis** [comment]
Checking

**Review by Caedis — APPROVED** [review]

**Pull request merged**
