### PR TITLE
Ability to disable ore generation in stalactites

### PR DESCRIPTION
**Pull request by Minepolz320**
I think this will make balance settings much more convenient for anyone who wants to use the mod in their modpacks

### CODE REVIEW

**Comment by Dream-Master** [comment]
You mean the ores in this Hill Caves? I would like to see generate GT ores instead. is this possible ?

**Comment by Dream-Master** [comment]
@Minepolz320 Are you able to make a second pr to add this integration?

**Comment by Minepolz320** [comment]
@Dream-Master I haven't thought about how to do this yet

**Comment by Minepolz320** [comment]
image
@Dream-Master 
In progress...

**Comment by Dream-Master** [comment]
Why you close it. Just use full ores .

**Comment by Minepolz320** [comment]
@Minepolz320 I wanted to mark it as a sketch but I don't know how 😅

**Pull request closed without merging**
